# ===== APPLICATION SETTINGS =====
spring.application.name=fuel_efficiency_interns
flight.xml.directory=../xml_files/
flight.year=2025
flight.month=10
# ===== SERVER SETTINGS =====
server.port=9998
server.host=localhost
# ===== SECURITY =====
jwt.secret=GqIiCyqnfST++VX0Q3X6rKoymywFM3p0s+eGMGece7ENSofQ6V0N8btUmfZ6KGvxm+LWG099k5ddkMLyGgJOsA==
admin.username=admin
admin.password=admin
# ===== PRIMARY DATASOURCE =====
spring.datasource.url=jdbc:postgresql://localhost:5432/new_db6
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ===== JPA/HIBERNATE =====
spring.jpa.datasource=POSTGRESQL

#spring.jpa.hibernate.ddl-auto=update
# ===== EXTERNAL DATASOURCES =====
# =====CORS=====
app.cors.allowed-ports=5173,3000
app.cors.allowed-origins=http://${server.host}:5173,http://${server.host}:3000

# ===== PILOT EFFICIENCY MODEL WEIGHTS =====
# Integral flight score: E = alpha * fuel + beta * punctuality + gamma * difficulty
app.efficiency.weights.fuel=0.4
app.efficiency.weights.punctuality=0.3
app.efficiency.weights.difficulty=0.3

# Flight difficulty score: D = wl * length + wn * night + ww * weather
app.difficulty.weights.length=0.34
app.difficulty.weights.night=0.33
app.difficulty.weights.weather=0.33
